"""add senha_provisoria

Revision ID: 3c477cc2169d
Revises: 
Create Date: 2026-06-29 20:18:41.576313

"""
from alembic import op
import sqlalchemy as sa


# identificadores usados pelo Alembic para encadear as migrations
revision = '3c477cc2169d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('senha_provisoria', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'senha_provisoria')
    # ### end Alembic commands ###
